#!/bin/bash

# remove libcxx first
cp libcxx* ../

# do this in build dir
cmake -Wno-dev -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_INSTALL_PREFIX=/root/build/ -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_PROJECTS="clang;compiler-rt;lld" -DLLVM_BINUTILS_INCDIR=/usr/include -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-alpine-linux-musl -DLLVM_HOST_TRIPLE=x86_64-alpine-linux-musl -DLLVM_BUILD_DOCS=OFF -DLLVM_BUILD_EXAMPLES=OFF \ -DCLANG_BUILD_EXAMPLES=OFF -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_ENABLE_ASSERTIONS=OFF -DLLVM_ENABLE_PIC=ON \ -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_SPHINX=OFF -DLLVM_ENABLE_TERMINFO=ON -DLLVM_ENABLE_ZLIB=ON -DLLVM_INCLUDE_EXAMPLES=OFF \ -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_APPEND_VC_REV=OFF -DCOMPILER_RT_INCLUDE_TESTS=ON -DCOMPILER_RT_BUILD_SANITIZERS=OFF  -DCOMPILER_RT_BUILD_XRAY=OFF -G "Unix Makefiles" ../llvm-project/llvm/
